# Use root/example as user/password credentials
version: '3.1'

services:
  api:
    build: .
    container_name: wanyue-api
    ports:
      - '13000:13000'
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: wanyue-db
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 8jdgi5anfkr2gm00rza1wvhjm2i9o4fl
      MYSQL_DATABASE: bok_app

    ports:
      - '12000:3306'
    networks:
      - app-network

# 添加网络配置
networks:
  app-network:
    driver: bridge
