# Use root/example as user/password credentials
version: '3.1'

services:
 nest-app:
    container_name: nest-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    # 定义该服务所依赖的其他服务，它们将按照依赖顺序启动
    depends_on:
      - db
    # 定义项目环境变量
    environment:
      - NODE_ENV=prod
    ports:
      - '13000:13000'
    networks:
      - app-network

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 8jdgi5anfkr2gm00rza1wvhjm2i9o4fl
      MYSQL_DATABASE: nestjs-backend
      MYSQL_USER: lizh
      MYSQL_PASSWORD: mch2lvy2o9vdo32md7bbs6kd2e7ctdcy
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '12000:3306'
    networks:
      - app-network

  # navicat
  adminer:
    image: adminer
    restart: always
    ports:
      - '12005:8080'
    networks:
      - app-network
    depends_on:
      - db

# 添加网络配置
networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
