name: Deploy to Server

on:
  push:
    branches: [main] # 当推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 将代码复制到服务器
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHPWD }}
          source: '.'
          target: '/home/blog/nest-api'

      # 在服务器上停止并构建应用
      - name: Build Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHPWD }}
          script: |
            cd /home/blog/nest-api
            docker compose down
            docker compose up -d --build
