name: Deploy to CentOS Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 将文件复制到服务器
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSHPWD }}
          source: './'
          target: /home/apps-server/wanyue-server/

      # SSH 连接服务器并重启应用
      - name: SSH to server and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSHPWD }}
          script: |
            cd /home/apps-server/wanyue-server
            npm install
            npm run build
            pm2 restart ./dist/src/main.js --name wanyue-server
