name: Deploy NestJS to Cloud Server via Docker

on:
  push:
    branches:
      - main # 你可以根据需求修改为其他分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout 代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 上传代码到云服务器
      - name: Upload code to cloud server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHPWD }}
          port: 22
          source: '.'
          target: '/home/wanyue-api/nestjs-backend'

      # 在云服务器上构建并运行 Docker 镜像
      - name: Build and run Docker image on server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSHPWD }} user@47.102.86.191 << 'EOF'
            cd /home/wanyue-api/nestjs-backend
            docker build -t NestApp .
            docker stop wanyue-api || true
            docker rm wanyue-api || true
            docker run -d --name wanyue-api -p 13000:13000 NestApp
          EOF
